### ISSUE TITLE
setup incubaid wiki

### ISSUE THREAD

**Issue by VonSub** [Incubaid/info_incubaid#1]
@nbabenko added you since @PeterNashaat is not in incubaid orgisation and I cannot add him. Please add him assign him this task.

**Comment by PeterNashaat** [comment]
it depend on this issue 
https://github.com/threefoldtech/home/issues/164
 will update here when we can start using this feature

**Comment by PeterNashaat** [comment]
wiki is deployed 
url for master branch : [link](https://info.incubaid.com/)
url for development branch : [link](https://www2.info.incubaid.com/)
